# =============================================================================
# CodeRabbit Configuration for MACROHARD Quantum OS
# =============================================================================
# Documentation: https://docs.coderabbit.ai/guides/configure-coderabbit

language: "en-US"

early_access: false

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  auto_title_placeholder: "@coderabbitai"
  review_status: true
  poem: false
  collapse_walkthrough: false
  sequence_diagrams: true
  changed_files_summary: true
  labeling_instructions: []
  path_filters: []
  path_instructions:
    - path: "redox/quantum_os/**/*.rs"
      instructions: |
        Review Rust code for:
        - Memory safety and proper use of unsafe blocks
        - Async/await patterns and Tokio best practices
        - Error handling with thiserror
        - Full snake_case naming per glossary.toml
        - LogosQ integration patterns
        - SIMD and parallel processing correctness
    - path: "redox/quantum_os/**/Cargo.toml"
      instructions: |
        Review Cargo configurations for:
        - Proper feature flag organization
        - Dependency version compatibility
        - Workspace inheritance patterns
    - path: "redox/quantum_os/docs/**"
      instructions: |
        Review documentation for:
        - Scientific accuracy
        - Citation completeness
        - Consistency with implementation

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  learnings:
    scope: "auto"
  issues:
    scope: "auto"
  jira:
    project_keys: []
  linear:
    team_keys: []
  pull_requests:
    scope: "auto"
